<?php

use App\Enums\AnnouncementFetcherType;

return [
    'sources' => [
        'school-homepage-latest-news' => [
            'name' => '學校首頁',
            'category' => '最新消息',
            'fetch_url' => 'https://www.nou.edu.tw/news1.aspx',
            'fetcher_type' => AnnouncementFetcherType::SCHOOL_HP->value,
            'fetcher_config' => [
                'base_url' => 'https://www.nou.edu.tw',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],

        // region 各處室
        'academic-affairs-course-selection' => [
            'name' => '教務處',
            'category' => '註冊選課',
            'fetch_url' => 'https://studadm.nou.edu.tw/api/AdvertApi?CategoryId=12&Page=1&take=999',
            'fetcher_type' => AnnouncementFetcherType::JSON_API->value,
            'fetcher_config' => [
                'base_url' => 'https://studadm.nou.edu.tw',
            ],
            'tracks_expiry' => true,
            'is_active' => true,
        ],
        'academic-affairs-tuition-waiver' => [
            'name' => '教務處',
            'category' => '學費減免',
            'fetch_url' => 'https://studadm.nou.edu.tw/api/AdvertApi?CategoryId=13&Page=1&take=999',
            'fetcher_type' => AnnouncementFetcherType::JSON_API->value,
            'fetcher_config' => [
                'base_url' => 'https://studadm.nou.edu.tw',
            ],
            'tracks_expiry' => true,
            'is_active' => true,
        ],
        'academic-affairs-credit-transfer' => [
            'name' => '教務處',
            'category' => '學分抵免',
            'fetch_url' => 'https://studadm.nou.edu.tw/api/AdvertApi?CategoryId=14&Page=1&take=999',
            'fetcher_type' => AnnouncementFetcherType::JSON_API->value,
            'fetcher_config' => [
                'base_url' => 'https://studadm.nou.edu.tw',
            ],
            'tracks_expiry' => true,
            'is_active' => true,
        ],
        'academic-affairs-graduation' => [
            'name' => '教務處',
            'category' => '畢業專區',
            'fetch_url' => 'https://studadm.nou.edu.tw/api/AdvertApi?CategoryId=15&Page=1&take=999',
            'fetcher_type' => AnnouncementFetcherType::JSON_API->value,
            'fetcher_config' => [
                'base_url' => 'https://studadm.nou.edu.tw',
            ],
            'tracks_expiry' => true,
            'is_active' => true,
        ],
        'academic-affairs-course-query' => [
            'name' => '教務處',
            'category' => '課程查詢',
            'fetch_url' => 'https://studadm.nou.edu.tw/api/AdvertApi?CategoryId=28&Page=1&take=999',
            'fetcher_type' => AnnouncementFetcherType::JSON_API->value,
            'fetcher_config' => [
                'base_url' => 'https://studadm.nou.edu.tw',
            ],
            'tracks_expiry' => true,
            'is_active' => true,
        ],
        'academic-affairs-video-seminar' => [
            'name' => '教務處',
            'category' => '視訊面授公告',
            'fetch_url' => 'https://studadm.nou.edu.tw/api/AdvertApi?CategoryId=35&Page=1&take=999',
            'fetcher_type' => AnnouncementFetcherType::JSON_API->value,
            'fetcher_config' => [
                'base_url' => 'https://studadm.nou.edu.tw',
            ],
            'tracks_expiry' => true,
            'is_active' => true,
        ],
        'academic-affairs-on-site-seminar' => [
            'name' => '教務處',
            'category' => '面授資訊',
            'fetch_url' => 'https://studadm.nou.edu.tw/api/AdvertApi?CategoryId=39&Page=1&take=999',
            'fetcher_type' => AnnouncementFetcherType::JSON_API->value,
            'fetcher_config' => [
                'base_url' => 'https://studadm.nou.edu.tw',
            ],
            'tracks_expiry' => true,
            'is_active' => true,
        ],
        'academic-affairs-exam-info' => [
            'name' => '教務處',
            'category' => '考試資訊',
            'fetch_url' => 'https://studadm.nou.edu.tw/api/AdvertApi?CategoryId=17&Page=1&take=999',
            'fetcher_type' => AnnouncementFetcherType::JSON_API->value,
            'fetcher_config' => [
                'base_url' => 'https://studadm.nou.edu.tw',
            ],
            'tracks_expiry' => true,
            'is_active' => true,
        ],
        'academic-affairs-summer-info' => [
            'name' => '教務處',
            'category' => '暑期資訊',
            'fetch_url' => 'https://studadm.nou.edu.tw/api/AdvertApi?CategoryId=38&Page=1&take=999',
            'fetcher_type' => AnnouncementFetcherType::JSON_API->value,
            'fetcher_config' => [
                'base_url' => 'https://studadm.nou.edu.tw',
            ],
            'tracks_expiry' => true,
            'is_active' => true,
        ],
        'academic-affairs-program-info' => [
            'name' => '教務處',
            'category' => '學程專區',
            'fetch_url' => 'https://studadm.nou.edu.tw/api/AdvertApi?CategoryId=45&Page=1&take=999',
            'fetcher_type' => AnnouncementFetcherType::JSON_API->value,
            'fetcher_config' => [
                'base_url' => 'https://studadm.nou.edu.tw',
            ],
            'tracks_expiry' => true,
            'is_active' => true,
        ],
        'academic-affairs-grade-info' => [
            'name' => '教務處',
            'category' => '成績資訊',
            'fetch_url' => 'https://studadm.nou.edu.tw/api/AdvertApi?CategoryId=46&Page=1&take=999',
            'fetcher_type' => AnnouncementFetcherType::JSON_API->value,
            'fetcher_config' => [
                'base_url' => 'https://studadm.nou.edu.tw',
            ],
            'tracks_expiry' => true,
            'is_active' => true,
        ],
        'academic-affairs-admissions-undergraduate' => [
            'name' => '教務處招生專區',
            'category' => '大學部招生簡章',
            'fetch_url' => 'https://studadm.nou.edu.tw/api/AdvertApi?CategoryId=18&Page=1&take=999',
            'fetcher_type' => AnnouncementFetcherType::JSON_API->value,
            'fetcher_config' => [
                'base_url' => 'https://studadm.nou.edu.tw',
            ],
            'tracks_expiry' => true,
            'is_active' => true,
        ],
        'academic-affairs-admissions-junior-college' => [
            'name' => '教務處招生專區',
            'category' => '專科部招生簡章',
            'fetch_url' => 'https://studadm.nou.edu.tw/api/AdvertApi?CategoryId=19&Page=1&take=999',
            'fetcher_type' => AnnouncementFetcherType::JSON_API->value,
            'fetcher_config' => [
                'base_url' => 'https://studadm.nou.edu.tw',
            ],
            'tracks_expiry' => true,
            'is_active' => true,
        ],
        // endregion

        // region 學系

        'humanity-department-latest-news' => [
            'name' => '人文學系',
            'category' => '最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/humanity/doclist.aspx?uid=4718&pid=4709',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/humanity',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'humanity-department-important-announcements' => [
            'name' => '人文學系',
            'category' => '重要公告',
            'fetch_url' => 'https://www2.nou.edu.tw/humanity/List.aspx?uid=4719&pid=4709',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/humanity',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'humanity-department-activities' => [
            'name' => '人文學系',
            'category' => '學系活動',
            'fetch_url' => 'https://www2.nou.edu.tw/humanity/List.aspx?uid=6249&pid=4709',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/humanity',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'humanity-department-general-announcements' => [
            'name' => '人文學系',
            'category' => '一般公告',
            'fetch_url' => 'https://www2.nou.edu.tw/humanity/List.aspx?uid=6250&pid=4709',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/humanity',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'humanity-department-exam-news' => [
            'name' => '人文學系',
            'category' => '考試消息',
            'fetch_url' => 'https://www2.nou.edu.tw/humanity/List.aspx?uid=4710&pid=4709',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/humanity',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'social-sciences-department-latest-news' => [
            'name' => '社會科學系',
            'category' => '最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/social/List.aspx?uid=4576&pid=4575',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/social',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'social-sciences-department-important-announcements' => [
            'name' => '社會科學系',
            'category' => '重要公告',
            'fetch_url' => 'https://www2.nou.edu.tw/social/List.aspx?uid=4584&pid=4575',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/social',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'business-department-live-updates' => [
            'name' => '商學系',
            'category' => '即時訊息',
            'fetch_url' => 'https://www2.nou.edu.tw/business/doclist.aspx?uid=3938&pid=3937',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/business',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'business-department-administrative-announcements' => [
            'name' => '商學系',
            'category' => '行政公告',
            'fetch_url' => 'https://www2.nou.edu.tw/business/List.aspx?uid=3946&pid=3937',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/business',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'public-administration-department-activities' => [
            'name' => '公共行政學系',
            'category' => '學系活動',
            'fetch_url' => 'https://www2.nou.edu.tw/pa/List.aspx?uid=3279&pid=3270',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/pa',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'public-administration-department-admissions-news' => [
            'name' => '公共行政學系',
            'category' => '招生訊息',
            'fetch_url' => 'https://www2.nou.edu.tw/pa/List.aspx?uid=3280&pid=3270',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/pa',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'public-administration-department-announcements' => [
            'name' => '公共行政學系',
            'category' => '系所公告',
            'fetch_url' => 'https://www2.nou.edu.tw/pa/List.aspx?uid=3271&pid=3270',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/pa',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'public-administration-department-other-announcements' => [
            'name' => '公共行政學系',
            'category' => '其他公告',
            'fetch_url' => 'https://www2.nou.edu.tw/pa/List.aspx?uid=4601&pid=3270',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/pa',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'living-sciences-department-latest-news' => [
            'name' => '生活科學系',
            'category' => '最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/living/List.aspx?uid=3743&pid=3742',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/living',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'living-sciences-department-announcements' => [
            'name' => '生活科學系',
            'category' => '系公告',
            'fetch_url' => 'https://www2.nou.edu.tw/living/List.aspx?uid=3751&pid=3742',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/living',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'living-sciences-department-activity-albums' => [
            'name' => '生活科學系',
            'category' => '活動相簿',
            'fetch_url' => 'https://www2.nou.edu.tw/living/albumList.aspx?album=249&uid=3746&pid=3742',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/living',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'management-and-information-department-bulletin' => [
            'name' => '管理與資訊學系',
            'category' => '公布欄',
            'fetch_url' => 'https://www2.nou.edu.tw/mi/doclist.aspx?uid=6059&pid=6058',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/mi',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'liberal-education-center-latest-news' => [
            'name' => '通識博雅教育中心',
            'category' => '中心最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/nouod/List.aspx?uid=4736&pid=4735',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/nouod',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'liberal-education-center-course-announcements' => [
            'name' => '通識博雅教育中心',
            'category' => '課程公告',
            'fetch_url' => 'https://www2.nou.edu.tw/nouod/List.aspx?uid=4744&pid=4735',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/nouod',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'liberal-education-center-admissions-news' => [
            'name' => '通識博雅教育中心',
            'category' => '招生訊息',
            'fetch_url' => 'https://www2.nou.edu.tw/nouod/List.aspx?uid=4992&pid=4735',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/nouod',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],

        // endregion

        // region 學習指導中心
        'keelung-center-latest-news' => [
            'name' => '基隆中心',
            'category' => '最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/keelung/List.aspx?uid=2275&pid=2274',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/keelung',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'keelung-center-special-class-news' => [
            'name' => '基隆中心',
            'category' => '專班最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/keelung/List.aspx?uid=2283&pid=2274',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/keelung',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'keelung-center-scholarship-news' => [
            'name' => '基隆中心',
            'category' => '獎學金',
            'fetch_url' => 'https://www2.nou.edu.tw/keelung/List.aspx?uid=2284&pid=2274',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/keelung',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'keelung-center-promotion-news' => [
            'name' => '基隆中心',
            'category' => '宣導專區',
            'fetch_url' => 'https://www2.nou.edu.tw/keelung/List.aspx?uid=5738&pid=2274',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/keelung',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'taipei-center-academic-news' => [
            'name' => '台北中心',
            'category' => '教務訊息',
            'fetch_url' => 'https://www2.nou.edu.tw/taipei/List.aspx?uid=3701&pid=3700',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/taipei',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'taipei-center-student-affairs-news' => [
            'name' => '台北中心',
            'category' => '學務訊息',
            'fetch_url' => 'https://www2.nou.edu.tw/taipei/List.aspx?uid=3709&pid=3700',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/taipei',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'taipei-center-scholarship-news' => [
            'name' => '台北中心',
            'category' => '獎學金',
            'fetch_url' => 'https://www2.nou.edu.tw/taipei/List.aspx?uid=3887&pid=3700',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/taipei',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'taipei-center-other-news' => [
            'name' => '台北中心',
            'category' => '其他訊息',
            'fetch_url' => 'https://www2.nou.edu.tw/taipei/List.aspx?uid=3710&pid=3700',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/taipei',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'taipei-center-honor-roll' => [
            'name' => '台北中心',
            'category' => '榮譽榜',
            'fetch_url' => 'https://www2.nou.edu.tw/taipei/List.aspx?uid=3711&pid=3700',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/taipei',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'matsu-office-latest-news' => [
            'name' => '馬祖辦公室',
            'category' => '中心最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/matsu/List.aspx?uid=2047&pid=2046',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/matsu',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'matsu-office-special-class-resources' => [
            'name' => '馬祖辦公室',
            'category' => '專班學習資源',
            'fetch_url' => 'https://www2.nou.edu.tw/matsu/List.aspx?uid=2055&pid=2046',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/matsu',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'taoyuan-center-academic-news' => [
            'name' => '桃園中心',
            'category' => '教務訊息',
            'fetch_url' => 'https://www2.nou.edu.tw/taoyuan/List.aspx?uid=3265&pid=3064',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/taoyuan',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'taoyuan-center-student-affairs-news' => [
            'name' => '桃園中心',
            'category' => '學務訊息',
            'fetch_url' => 'https://www2.nou.edu.tw/taoyuan/List.aspx?uid=6662&pid=3064',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/taoyuan',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'taoyuan-center-scholarship-news' => [
            'name' => '桃園中心',
            'category' => '獎學金訊息',
            'fetch_url' => 'https://www2.nou.edu.tw/taoyuan/List.aspx?uid=6663&pid=3064',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/taoyuan',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'taoyuan-center-other-news' => [
            'name' => '桃園中心',
            'category' => '其他訊息',
            'fetch_url' => 'https://www2.nou.edu.tw/taoyuan/List.aspx?uid=3073&pid=3064',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/taoyuan',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'taoyuan-center-calendar' => [
            'name' => '桃園中心',
            'category' => '行事曆',
            'fetch_url' => 'https://www2.nou.edu.tw/taoyuan/List.aspx?uid=3186&pid=3064',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/taoyuan',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'taoyuan-center-honor-roll' => [
            'name' => '桃園中心',
            'category' => '榮譽榜',
            'fetch_url' => 'https://www2.nou.edu.tw/taoyuan/List.aspx?uid=3075&pid=3064',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/taoyuan',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'hsinchu-center-announcements' => [
            'name' => '新竹中心',
            'category' => '中心公告',
            'fetch_url' => 'https://www2.nou.edu.tw/hsinchu/List.aspx?uid=218&pid=10',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/hsinchu',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'hsinchu-center-special-class-announcements' => [
            'name' => '新竹中心',
            'category' => '專班公告',
            'fetch_url' => 'https://www2.nou.edu.tw/hsinchu/List.aspx?uid=220&pid=10',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/hsinchu',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'hsinchu-center-club-announcements' => [
            'name' => '新竹中心',
            'category' => '社團公告',
            'fetch_url' => 'https://www2.nou.edu.tw/hsinchu/List.aspx?uid=5214&pid=10',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/hsinchu',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'hsinchu-center-student-support-announcements' => [
            'name' => '新竹中心',
            'category' => '學輔公告',
            'fetch_url' => 'https://www2.nou.edu.tw/hsinchu/List.aspx?uid=5433&pid=10',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/hsinchu',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'hsinchu-center-calendar' => [
            'name' => '新竹中心',
            'category' => '中心行事曆',
            'fetch_url' => 'https://www2.nou.edu.tw/hsinchu/List.aspx?uid=215&pid=10',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/hsinchu',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'hsinchu-center-scholarship-announcements' => [
            'name' => '新竹中心',
            'category' => '獎學金公告',
            'fetch_url' => 'https://www2.nou.edu.tw/hsinchu/List.aspx?uid=5885&pid=10',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/hsinchu',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'taichung-center-latest-news' => [
            'name' => '台中中心',
            'category' => '最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/taichung/doclist.aspx?uid=2554&pid=2553',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/taichung',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'taichung-center-special-class-news' => [
            'name' => '台中中心',
            'category' => '專班最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/taichung/List.aspx?uid=2562&pid=2553',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/taichung',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'taichung-center-student-affairs-news' => [
            'name' => '台中中心',
            'category' => '學務最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/taichung/List.aspx?uid=2563&pid=2553',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/taichung',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'taichung-center-freshman-news' => [
            'name' => '台中中心',
            'category' => '新生專區',
            'fetch_url' => 'https://www2.nou.edu.tw/taichung/List.aspx?uid=5476&pid=5476',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/taichung',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'changhua-office-freshman-zone' => [
            'name' => '彰化辦公室',
            'category' => '新生專區',
            'fetch_url' => 'https://www2.nou.edu.tw/changhua/List.aspx?uid=5879&pid=5879',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/changhua',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'changhua-office-latest-news' => [
            'name' => '彰化辦公室',
            'category' => '中心最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/changhua/List.aspx?uid=2815&pid=2814',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/changhua',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'changhua-office-special-class-news' => [
            'name' => '彰化辦公室',
            'category' => '專班最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/changhua/List.aspx?uid=2823&pid=2814',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/changhua',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'changhua-office-club-news' => [
            'name' => '彰化辦公室',
            'category' => '社團最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/changhua/List.aspx?uid=2824&pid=2814',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/changhua',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'changhua-office-honor-roll' => [
            'name' => '彰化辦公室',
            'category' => '榮譽榜',
            'fetch_url' => 'https://www2.nou.edu.tw/changhua/List.aspx?uid=2825&pid=2814',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/changhua',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'nantou-office-freshman-zone' => [
            'name' => '南投辦公室',
            'category' => '新生專區',
            'fetch_url' => 'https://www2.nou.edu.tw/nantou/List.aspx?uid=5880&pid=5880',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/nantou',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'nantou-office-current-semester-courses' => [
            'name' => '南投辦公室',
            'category' => '當學期開課資料',
            'fetch_url' => 'https://www2.nou.edu.tw/nantou/List.aspx?uid=3175&pid=2935',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/nantou',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'nantou-office-events-calendar' => [
            'name' => '南投辦公室',
            'category' => '活動行事曆',
            'fetch_url' => 'https://www2.nou.edu.tw/nantou/calenderList.aspx?uid=3039&pid=2935',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/nantou',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'chiayi-center-latest-news' => [
            'name' => '嘉義中心',
            'category' => '中心最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/chiayi/List.aspx?uid=3510&pid=3509',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/chiayi',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'chiayi-center-important-announcements' => [
            'name' => '嘉義中心',
            'category' => '重要宣導',
            'fetch_url' => 'https://www2.nou.edu.tw/chiayi/List.aspx?uid=3518&pid=3509',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/chiayi',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'chiayi-center-student-support' => [
            'name' => '嘉義中心',
            'category' => '就學輔助',
            'fetch_url' => 'https://www2.nou.edu.tw/chiayi/List.aspx?uid=3519&pid=3509',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/chiayi',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'yunlin-office-latest-news' => [
            'name' => '雲林辦公室',
            'category' => '中心最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/yunlin/List.aspx?uid=2320&pid=2319',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/yunlin',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'yunlin-office-special-class-news' => [
            'name' => '雲林辦公室',
            'category' => '專班最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/yunlin/List.aspx?uid=2328&pid=2319',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/yunlin',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'yunlin-office-club-news' => [
            'name' => '雲林辦公室',
            'category' => '社團最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/yunlin/List.aspx?uid=2329&pid=2319',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/yunlin',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'yunlin-office-events-calendar' => [
            'name' => '雲林辦公室',
            'category' => '活動行事曆',
            'fetch_url' => 'https://www2.nou.edu.tw/yunlin/calenderList.aspx?uid=2414&pid=2319',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/yunlin',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'tainan-center-latest-news' => [
            'name' => '台南中心',
            'category' => '中心最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/tainan/List.aspx?uid=16&pid=179',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/tainan',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'tainan-center-special-class-news' => [
            'name' => '台南中心',
            'category' => '專班最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/tainan/List.aspx?uid=177&pid=179',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/tainan',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'tainan-center-honor-roll' => [
            'name' => '台南中心',
            'category' => '榮譽榜',
            'fetch_url' => 'https://www2.nou.edu.tw/tainan/List.aspx?uid=180&pid=179',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/tainan',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'tainan-center-kongnan-news' => [
            'name' => '台南中心',
            'category' => '空南學訊（一定要看）',
            'fetch_url' => 'https://www2.nou.edu.tw/tainan/List.aspx?uid=3507&pid=179',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/tainan',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'tainan-center-calendar' => [
            'name' => '台南中心',
            'category' => '行事曆',
            'fetch_url' => 'https://www2.nou.edu.tw/tainan/List.aspx?uid=5207&pid=179',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/tainan',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'kaohsiung-center-latest-news' => [
            'name' => '高雄中心',
            'category' => '最新消息',
            'fetch_url' => 'https://kaohsiung.nou.edu.tw/news_idx.aspx',
            'fetcher_type' => AnnouncementFetcherType::HTML_NEWS_BOX->value,
            'fetcher_config' => [
                'base_url' => 'https://kaohsiung.nou.edu.tw',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'yilan-center-latest-news' => [
            'name' => '宜蘭中心',
            'category' => '中心最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/yilan/List.aspx?uid=2600&pid=2599',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/yilan',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'yilan-center-special-class-news' => [
            'name' => '宜蘭中心',
            'category' => '專班最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/yilan/List.aspx?uid=2609&pid=2599',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/yilan',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'hualien-center-latest-news' => [
            'name' => '花蓮中心',
            'category' => '中心最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/hualien/List.aspx?uid=3091&pid=3090',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/hualien',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'hualien-center-special-class-news' => [
            'name' => '花蓮中心',
            'category' => '專班最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/hualien/List.aspx?uid=3099&pid=3090',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/hualien',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'hualien-center-club-news' => [
            'name' => '花蓮中心',
            'category' => '社團最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/hualien/List.aspx?uid=3100&pid=3090',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/hualien',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'hualien-center-honor-roll' => [
            'name' => '花蓮中心',
            'category' => '榮譽榜',
            'fetch_url' => 'https://www2.nou.edu.tw/hualien/List.aspx?uid=3101&pid=3090',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/hualien',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'taitung-center-latest-news' => [
            'name' => '台東中心',
            'category' => '中心最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/TAiTung/List.aspx?uid=2298&pid=2297',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/TAiTung',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'taitung-center-special-class-news' => [
            'name' => '台東中心',
            'category' => '專班最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/TAiTung/List.aspx?uid=2306&pid=2297',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/TAiTung',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'taitung-center-club-news' => [
            'name' => '台東中心',
            'category' => '社團最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/TAiTung/List.aspx?uid=2307&pid=2297',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/TAiTung',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'penghu-center-latest-news' => [
            'name' => '澎湖中心',
            'category' => '中心最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/penghu/List.aspx?uid=2576&pid=2575',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/penghu',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'penghu-center-honor-roll' => [
            'name' => '澎湖中心',
            'category' => '榮譽榜',
            'fetch_url' => 'https://www2.nou.edu.tw/penghu/List.aspx?uid=2585&pid=2575',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/penghu',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'penghu-center-monthly-important-news' => [
            'name' => '澎湖中心',
            'category' => '每月重要訊息',
            'fetch_url' => 'https://www2.nou.edu.tw/penghu/List.aspx?uid=2584&pid=2575',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/penghu',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'kinmen-center-latest-news' => [
            'name' => '金門中心',
            'category' => '中心最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/kinmen/List.aspx?uid=2115&pid=2114',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/kinmen',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'kinmen-center-special-class-news' => [
            'name' => '金門中心',
            'category' => '專班最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/kinmen/List.aspx?uid=2123&pid=2114',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/kinmen',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'kinmen-center-club-news' => [
            'name' => '金門中心',
            'category' => '社團最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/kinmen/List.aspx?uid=2124&pid=2114',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/kinmen',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'overseas-student-services-latest-news' => [
            'name' => '海外學生服務組',
            'category' => '中心最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/overseas/List.aspx?uid=4084&pid=4083',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/overseas',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'overseas-student-services-affairs-news' => [
            'name' => '海外學生服務組',
            'category' => '學務最新消息',
            'fetch_url' => 'https://www2.nou.edu.tw/overseas/List.aspx?uid=4092&pid=4083',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/overseas',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'overseas-student-services-activities-other' => [
            'name' => '海外學生服務組',
            'category' => '活動轉知 / 其他',
            'fetch_url' => 'https://www2.nou.edu.tw/overseas/List.aspx?uid=4093&pid=4083',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/overseas',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        'overseas-student-services-honor-roll' => [
            'name' => '海外學生服務組',
            'category' => '榮譽榜',
            'fetch_url' => 'https://www2.nou.edu.tw/overseas/List.aspx?uid=4094&pid=4083',
            'fetcher_type' => AnnouncementFetcherType::HTML_SCRAPE->value,
            'fetcher_config' => [
                'base_url' => 'https://www2.nou.edu.tw/overseas',
            ],
            'tracks_expiry' => false,
            'is_active' => true,
        ],
        // endregion
    ],
];
